module.exports = {
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  CHAT_START: 'CHAT_START',
  CHANNEL_SET: 'CHANNEL_SET',
  CHANNEL_LEAVE: 'CHANNEL_LEAVE',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  TYPING: 'TYPING',
}
